fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    mysql: "puppetlabs/mysql"
    inifile: "puppetlabs/inifile"
    supervisor: "proletaryo/supervisor"
    epel: "stahnma/epel"
  symlinks:
    mha: "#{source_dir}"
