#!/bin/sh
# MHA helper script

set -e

usage() {
    prog=$(basename $0)
    cat <<EOM 1>&2
Usage:
    # show help
    $prog -h

    # for online master of app_name switch
    $prog app_name

    # batch mode (non-interactive)
    $prog [-b] app_name

EOM
    exit 1
}

interactive=1

while getopts bh OPT
do
    case $OPT in
        h)
            usage
            ;;
        b) # batch mode
            interactive=0
            ;;
        *)
            usage
            ;;
    esac
done

shift $(expr $OPTIND - 1)

app_name="$1"
[ -n "$app_name" ] || usage

/usr/bin/masterha_master_switch \
  --conf=/etc/masterha/${app_name}.cnf \
  --interactive=$interactive \
  --master_state=alive \
  --orig_master_is_new_slave

